#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
name: Filtering Actions Workflow
on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'feature/**'
      - '!feature/featC'
    #branches-ignore:
    #  -
    tags: 
      - v1.*
    paths:
      - '**.js'
      - '!filename.js'
    #paths-ignore:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
